### ISSUE TITLE
Getting error when using After-effects Library

### ISSUE THREAD

**Issue by manishgurnaney** [BenZed/after-effects#23]
Hi All,
      I am using after-effects library, with ae-to-json package but, I am getting issues as 

		this.includes = [...codify_includes(this.options.includes, this.options.minify), babelIncludes];
		                 ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
 

Following is the code which I am using 

var aeToJSON = require('ae-to-json/after-effects');
var ae = require('after-effects');
var fs = require('fs-extra');
ae.execute(aeToJSON)
.then(function(json) {
  console.log(json);  
})
.catch(function(e) {
  throw e;
});

--Please correct me If I am missing some thing.

**Comment by BenZed** [comment]
I wrote this package without a transpiler (which is actually pretty ironic, because it uses a transpiler)

Your current version of Node must not have support for the [Spread/Rest operator](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Spread_operator), so it 's crashing.

Upgrading your Node will fix this problem.

Alternatively, an updated version is currently in development that will work on all node version. So, if you don't want to upgrade, sit tight! There will be a fix out in a couple of days.

**Comment by manishgurnaney** [comment]
Hi BenZed,
               Thanks a lot for the input, this issue is solved. But now I am having a different issue :- 

/Users/gurnaneymanish/Documents/node_modules/after-effects/index.js:79
    throw new Error(Errors.BadExecuteArgument);
    ^
Error: execute expects a function or AfterEffectsCommand instance.
    at prepare_command (/Users/gurnaneymanish/Documents/node_modules/after-effects/index.js:79:11)
    at Function.execute (/Users/gurnaneymanish/Documents/node_modules/after-effects/index.js:144:19)
    at Object.<anonymous> (/Users/gurnaneymanish/Documents/AERoJSon/aeToJSON.js:4:4)


I am using the above script in Mac, is this releated to Mac os.

**Comment by BenZed** [comment]
Not sure, I'd say that's non the 'ae-to-json' package end.

According to it's readme, you're using the correct code, though. Anyway the error message just means that you need to supply a **function** or a **Command** object to **ae** for it to work.
